job/urls.py
from unicodedata import name
from job import views
from django.urls import path

from django.urls.conf import include
from job import viewsapi
"""the app_name variable provided for {% url 'namespace-for-url-ofproject:the nameofviewinpath' and relate it with id%}"""
app_name='job'


urlpatterns = [
    path('',views.job_list,name="job_list"),
    path('add',views.add_job,name="add_job"),
    path('<str:slug>',views.job_detail,name="job_detail"),
    #Generic Class Based Views Api
    path('api/jobs',viewsapi.Job_ListApi.as_view(),name='job_list_api'),
    path('api/jobs/<int:id>',viewsapi.Job_DetailApi.as_view(),name='job_detail_api'),
    path('api/category',viewsapi.Category_ListApi.as_view(),name='category_list_api'),
    path('api/category/<int:id>',viewsapi.Category_DetailApi.as_view(),name='category_detail_api'),
    path('api/apply',viewsapi.Apply_ListApi.as_view(),name='apply_list_api'),
    path('api/apply/<int:id>',viewsapi.Apply_DetailApi.as_view(),name='apply_detail_api'),
    #End of Generic Class Based Views Api

    #Function Based Views Api
    path('api/jobsfunc',viewsapi.job_list_func_api , name='job_list_func_api'),
    path('api/jobsfunc/<int:id>',viewsapi.job_detail_func_api , name='job_detail_func_api'),
    path('api/categoryfunc',viewsapi.Category_list_func_api , name='Category_list_func_api'),
    path('api/categoryfunc/<int:id>',viewsapi.Category_detail_func_api , name='Category_detail_func_api'),
    path('api/applyfunc',viewsapi.Apply_list_func_api , name='Apply_list_func_api'),
    path('api/applyfunc/<int:id>',viewsapi.Apply_detail_func_api , name='Apply_detail_func_api'),
    #End of Function Based Views Api
    
]

project/urls.py
from unicodedata import name
from django import views
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace="accounts")),
    path('admin/', admin.site.urls),
    path('jobs/',include('job.urls',namespace="jobs")),
    path('contacts/',include('contact.urls',namespace="contact")),
    path('api-auth/',include("rest_framework.urls")),
    path('blog/',include('blog.urls',namespace="blogs")),
    path('',include('home.urls',namespace="homepage")),
    
]

urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

job/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User
# Create your models here.

job_choice=(
    ('Full-Time','Full-Time'),
    ('Part-Time','Part-Time'),
)

# this function image_upload for uploading images from image field in Job model (saving the images with this beginword "job_img"+instanceid.extension)
def image_upload(instance,filename):
    txt='imgjob_'
    imagename,extension=filename.split('.')
    return "jobs/%s%s.%s"%(txt,instance.id,extension)

class State(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Region(models.Model):
    name = models.CharField(max_length=50)
    state = models.ForeignKey(State, related_name='regions', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Job(models.Model):
    owner = models.ForeignKey(User, related_name='job_owner', on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    job_type = models.CharField(max_length=15, choices=job_choice)
    description = models.TextField(max_length=1000)
    published_at = models.DateTimeField(auto_now=True)
    vacancy = models.IntegerField(default=1)
    salary = models.IntegerField(default=0)
    experience = models.IntegerField(default=1)
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    image = models.ImageField(upload_to=image_upload)
    slug = models.SlugField(blank=True, null=True)
    address = models.CharField(max_length=100, blank=True, null=True)
    region = models.ForeignKey(Region, related_name='jobs', on_delete=models.CASCADE, blank=True, null=True)
    state = models.ForeignKey(State, related_name='jobs', on_delete=models.CASCADE, blank=True, null=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Job, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

class Category(models.Model):
    name = models.CharField(max_length=25)

    def __str__(self):
        return self.name

class apply(models.Model):
    job = models.ForeignKey(Job, related_name='apply_job', on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=100)
    website = models.URLField()
    cv = models.FileField(upload_to='apply/')
    cover_letter = models.TextField(max_length=500)
    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

job/forms.py
from django import forms
from django.forms import fields


from .models import apply,Job

class ApplyForm(forms.ModelForm):
    class Meta():
        model = apply
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Your name'}),
            'email': forms.EmailInput(attrs={'placeholder': 'Email'}),
            'website': forms.URLInput(attrs={'placeholder': 'Website/Portfolio link'}),
            'cv': forms.FileInput(attrs={'placeholder': 'Upload CV','id':'inputGroupFile03', 'aria-describedby':'inputGroupFileAddon03'}),
            'cover_letter': forms.Textarea(
                attrs={'placeholder': 'Enter CoverLetter here','cols':'30', 'rows':'10'}),
        }

        fields = ['name','email','website','cv','cover_letter']



class JobForm(forms.ModelForm):
    class Meta():
        model=Job
        fields="__all__"
        exclude=('slug','owner')







        

job/views.py
from django.shortcuts import redirect, render
from .models import Job
from django.core.paginator import Paginator
from django.urls import reverse
from .forms import ApplyForm,JobForm
from django.contrib.auth.decorators import login_required
from .filters import JobFilter
# Create your views here.

def job_list(request):
    job_list=Job.objects.all()
    #Filter Section:We will pass all job_list to Jobfilter to filter all the results then pass the filtering job_list to the paginator
    myfilter=JobFilter(request.GET,queryset=job_list)
    job_list=myfilter.qs

    paginator=Paginator(job_list,10)
    page_number=request.GET.get('page')
    page_obj=paginator.get_page(page_number)
    context={'jobs':page_obj,'myjobfilter':myfilter}
    return render(request,'job/job_list.html',context)





def job_detail(request,slug):
    job_detail=Job.objects.get(slug=slug)
    if request.method=='POST':
        form=ApplyForm(request.POST,request.FILES)
        if form.is_valid():
            myform=form.save(commit=False)
            myform.job=job_detail
            myform.save()
            form=ApplyForm() #this line is for clear all form fields after submitting
            print('Succesfully Submit')
    else:
        form=ApplyForm()


    context={'job':job_detail,'jobform':form}
    return render(request,'job/job_detail.html',context)
    

    #myform.job[is the name of the field in apply form]=job_detail[is for know that we are apply the same job]

#We add decorator For force the user to login first then he can post a job(only Users have login can post job)

@login_required
def add_job(request):
    if request.method=="POST":
        form=JobForm(request.POST,request.FILES)
        if form.is_valid():
            myform=form.save(commit=False)
            myform.owner=request.user
            myform.save()
            form=JobForm() #this line is for clear all form fields after submitting
            return redirect(reverse('jobs:job_list'))
    else:
        form=JobForm()
    

        
    return render(request,'job/add_job.html',{'postform':form})

job/templates/job/add_job.html
{% extends 'base.html' %}

{% block body %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>ADD NEW JOB</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 mx-auto">
                    
                    
                    
                    <div class="apply_job_form white-bg">
                        <h4>Post New Job</h4>
                        <form method='POST' enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="input_field">
                                        <label for="">Title: </label>
                                        <br>
                                        {{postform.title}}
                                        
                                    </div>
                                </div>
                                
                                
                                <div class="col-md-12">
                                    <div class="input_field">
                                       <!-- <input type="text" placeholder="Email">-->
                                       <label for="">Job Type: </label>
                                       <br>
                                       {{postform.job_type}}
                                       
                                    </div>
                                </div>
                                
                                <div class="col-md-12">
                                    <div class="input_field">
                                        <!--<input type="text" placeholder="Website/Portfolio link">-->
                                        <label for="">Description: </label>
                                        <br>
                                        {{postform.description}}
                                        
                                    </div>
                                </div>
                               
                                <div class="col-md-12">
                                    <div class="input_field">
                                        <!--<input type="text" placeholder="Website/Portfolio link">-->
                                        <label for="">Vacancy: </label>
                                        <br>
                                        {{postform.vacancy}}
                                        
                                    </div>
                                </div>
                                
                                <div class="col-md-12">
                                    <div class="input_field">
                                        <!--<input type="text" placeholder="Website/Portfolio link">-->
                                        <label for="">Salary:</label>
                                        <br>
                                        {{postform.salary}}
                                        
                                    </div>
                                </div>
                                 <div class="col-md-12">
                                    <div class="input_field">
                                        <!--<input type="text" placeholder="Website/Portfolio link">-->
                                        <label for="">Experience:</label>
                                        <br>
                                        {{postform.experience}}
                                        
                                    </div>
                                </div>
                                
                                <div class="col-md-12">
                                    <div class="input_field">
                                        <!--<textarea name="#" id="" cols="30" rows="10" placeholder="Coverletter"></textarea>-->
                                        <label for="">Category: </label>
                                        <br>
                                        {{postform.category}}
                                        
                                        
                                    </div>
                                </div>
                                
                                <div class="col-md-12">
                                        <label for="">Image</label>
                                        <br>
                                    
                                    <div class="input-group">
                                        <div class="input-group-prepend">
                                          <button type="button"  id="inputGroupFileAddon03" ><i class="fa fa-cloud-upload" aria-hidden="true" ></i>
                                          <i>Upload Image</i>
                                          </button>
                                        </div>
                                        <div class="custom-file">
                                          <!--<input type="file" class="custom-file-input" id="inputGroupFile03" aria-describedby="inputGroupFileAddon03">-->
                                          {{postform.image}}
                                        </div>
                                    </div>
                                </div>
                                <br>
                                <div class="col-md-12">
                                    <div class="submit_btn">
                                        <button class="boxed-btn3 w-100" type="submit">Post Now</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>

    {% endblock body %}

job/templates/job/job_detail.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/custom.css' %}">
{% endblock %}

{% block body %}
<!-- Job Detail Header -->
<div class="container py-4">
  <div class="row">
    <div class="col-12">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb bg-transparent p-0">
          <li class="breadcrumb-item"><a href="{% url 'jobs:job_list' %}">Jobs</a></li>
          <li class="breadcrumb-item active" aria-current="page">{{job.title}}</li>
        </ol>
      </nav>
    </div>
  </div>
</div>

<!-- Job Detail Content -->
<div class="container pb-5">
  <div class="row">
    <!-- Main Content Area -->
    <div class="col-lg-8">
      <!-- Job Header Card -->
      <div class="card border-0 shadow-sm mb-4">
        <div class="card-body p-4">
          <div class="d-flex">
            <div class="company-logo-container bg-light rounded d-flex align-items-center justify-content-center me-4" style="width: 100px; height: 100px;">
              <img src="{{job.image.url}}" class="img-fluid p-2" alt="{{job.title}}" style="max-width: 80px; max-height: 80px;">
            </div>
            <div>
              <h1 class="h2 mb-2">{{job.title}}</h1>
              <div class="d-flex flex-wrap gap-3 mb-3">
                <div class="d-flex align-items-center text-muted">
                  <i class="bi bi-geo-alt me-2"></i>
                  <span>California, USA</span>
                </div>
                <div class="d-flex align-items-center text-muted">
                  <i class="bi bi-clock me-2"></i>
                  <span>{{job.job_type}}</span>
                </div>
                <div class="d-flex align-items-center text-muted">
                  <i class="bi bi-currency-dollar me-2"></i>
                  <span>{{job.salary}}k/year</span>
                </div>
              </div>
              <a href="#apply-section" class="btn btn-success px-4">
                <i class="bi bi-send me-2"></i>Apply Now
              </a>
            </div>
          </div>
        </div>
      </div>

      <!-- Job Description -->
      <div class="card border-0 shadow-sm mb-4">
        <div class="card-body p-4">
          <h4 class="card-title mb-4">Job Description</h4>
          <div class="job-description">
            <p>{{job.description}}</p>
          </div>
        </div>
      </div>

      <!-- Application Form -->
      <div class="card border-0 shadow-sm" id="apply-section">
        <div class="card-body p-4">
          <h4 class="card-title mb-4">Apply for this Job</h4>
          
          <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row g-3">
              <div class="col-md-6">
                <label for="id_name" class="form-label">Full Name</label>
                <div class="form-group">
                  {% bootstrap_field jobform.name show_label=False placeholder="Enter your full name" %}
                </div>
              </div>
              <div class="col-md-6">
                <label for="id_email" class="form-label">Email Address</label>
                <div class="form-group">
                  {% bootstrap_field jobform.email show_label=False placeholder="Enter your email" %}
                </div>
              </div>
              <div class="col-md-12">
                <label for="id_website" class="form-label">Website/Portfolio (Optional)</label>
                <div class="form-group">
                  {% bootstrap_field jobform.website show_label=False placeholder="https://your-portfolio.com" %}
                </div>
              </div>
              <div class="col-md-12">
                <label for="id_cv" class="form-label">Resume/CV</label>
                <div class="input-group">
                  <span class="input-group-text bg-light">
                    <i class="bi bi-file-earmark-pdf"></i>
                  </span>
                  <div class="form-control-file">
                    {% bootstrap_field jobform.cv show_label=False %}
                  </div>
                </div>
                <div class="form-text text-muted">Upload your CV (PDF, DOC, DOCX)</div>
              </div>
              <div class="col-md-12">
                <label for="id_cover_letter" class="form-label">Cover Letter</label>
                <div class="form-group">
                  {% bootstrap_field jobform.cover_letter show_label=False %}
                </div>
                <div class="form-text text-muted">Explain why you're a good fit for this position</div>
              </div>
              <div class="col-md-12 mt-4">
                <button type="submit" class="btn btn-success btn-lg w-100">
                  <i class="bi bi-check2-circle me-2"></i>Submit Application
                </button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>

    <!-- Sidebar -->
    <div class="col-lg-4 mt-4 mt-lg-0">
      <!-- Job Summary Card -->
      <div class="card border-0 shadow-sm mb-4">
        <div class="card-header bg-light py-3">
          <h5 class="mb-0">Job Summary</h5>
        </div>
        <div class="card-body p-4">
          <ul class="list-unstyled mb-0">
            <li class="d-flex justify-content-between py-2 border-bottom">
              <span class="text-muted">Published on:</span>
              <span class="fw-medium">{{job.published_at|date:'d M o'}}</span>
            </li>
            <li class="d-flex justify-content-between py-2 border-bottom">
              <span class="text-muted">Vacancy:</span>
              <span class="fw-medium">{{job.vacancy}} Position</span>
            </li>
            <li class="d-flex justify-content-between py-2 border-bottom">
              <span class="text-muted">Salary:</span>
              <span class="fw-medium">{{job.salary}}k/year</span>
            </li>
            <li class="d-flex justify-content-between py-2 border-bottom">
              <span class="text-muted">Location:</span>
              <span class="fw-medium">California, USA</span>
            </li>
            <li class="d-flex justify-content-between py-2">
              <span class="text-muted">Job Type:</span>
              <span class="fw-medium">{{job.job_type}}</span>
            </li>
          </ul>
        </div>
      </div>

      <!-- Share Card -->
      <div class="card border-0 shadow-sm mb-4">
        <div class="card-body p-4">
          <h5 class="card-title mb-3">Share This Job</h5>
          <div class="d-flex gap-2">
            <a href="#" class="btn btn-outline-primary">
              <i class="bi bi-facebook"></i>
            </a>
            <a href="#" class="btn btn-outline-danger">
              <i class="bi bi-google"></i>
            </a>
            <a href="#" class="btn btn-outline-info">
              <i class="bi bi-twitter"></i>
            </a>
            <a href="#" class="btn btn-outline-secondary">
              <i class="bi bi-linkedin"></i>
            </a>
            <a href="#" class="btn btn-outline-success">
              <i class="bi bi-envelope"></i>
            </a>
          </div>
        </div>
      </div>

      <!-- Location Card -->
      <div class="card border-0 shadow-sm">
        <div class="card-header bg-light py-3">
          <h5 class="mb-0">Job Location</h5>
        </div>
        <div class="card-body p-0">
          <div class="ratio ratio-16x9">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d26430.393553120906!2d-118.43209796322542!3d34.08346349319247!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x80c2bc35fbd217ef%3A0xcf1ef9352700d95c!2sBeverly%20Hills%2C%20CA%2090210!5e0!3m2!1sen!2sus!4v1647624992276!5m2!1sen!2sus" 
                  style="border:0;" allowfullscreen="" loading="lazy"></iframe>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock body %}

job/templates/job/job_list.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/card.css' %}"/>
{% endblock %}

{% block body %}
<div class="container py-4">
    <div class="row">
        <!-- Filter Sidebar -->
        <div class="col-lg-3 mb-4">
            {% include "job/components/filter_sidebar.html" with filter_form=myjobfilter.form %}
        </div>
        
        <!-- Job Listings -->
        <div class="col-lg-9">
            <!-- Job Listing Header -->
            {% include "job/components/listing_header.html" with title="Job Listing" %}

            <!-- Job List Items -->
            <div class="job-list">
                {% for job in jobs %}
                    {% include "job/components/job_item.html" with job=job %}
                {% empty %}
                    <div class="alert alert-info">No jobs found matching your criteria.</div>
                {% endfor %}
            </div>

            <!-- Pagination -->
            {% include "job/components/pagination.html" with page_obj=jobs %}
        </div>
    </div>
</div>
{% endblock body %}