blog/urls.py
from unicodedata import name
from blog import views
from django.urls import path
from django.urls.conf import include
from blog import viewsapi
"""the app_name variable provided for {% url 'namespace-for-url-ofproject:the nameofviewinpath' and relate it with id%}"""
app_name='blog'


urlpatterns = [
    path('',views.blog_list,name="blog_list"),
    path('addpost',views.create_post,name="blog_create_post"),
    path('post_detail/<str:slug>',views.blog_detail,name="blog_detail"),
      #Generic Class Based Views Api
    path('api/post',viewsapi.Post_ListApi.as_view(),name='post_list_api'),
    path('api/post/<int:id>',viewsapi.Post_DetailApi.as_view(),name='post_detail_api'),
    path('api/comment',viewsapi.Comment_ListApi.as_view(),name='comment_list_api'),
    path('api/comment/<int:id>',viewsapi.Comment_DetailApi.as_view(),name='comment_detail_api'),

    #End of Generic Class Based Views Api

    #Function Based Views Api
    path('api/postfunc',viewsapi.Post_list_func_api , name='post_list_func_api'),
    path('api/postfunc/<int:id>',viewsapi.Post_detail_func_api , name='post_detail_func_api'),
    path('api/commentfunc',viewsapi.Comment_list_func_api , name='Comment_list_func_api'),
    path('api/commentfunc/<int:id>',viewsapi.Comment_detail_func_api , name='Comment_detail_func_api'),

    #End of Function Based Views Api
    
    
]

job/urls.py
from unicodedata import name
from job import views
from django.urls import path

from django.urls.conf import include
from job import viewsapi
"""the app_name variable provided for {% url 'namespace-for-url-ofproject:the nameofviewinpath' and relate it with id%}"""
app_name='job'


urlpatterns = [
    path('',views.job_list,name="job_list"),
    path('add',views.add_job,name="add_job"),
    path('<str:slug>',views.job_detail,name="job_detail"),
    #Generic Class Based Views Api
    path('api/jobs',viewsapi.Job_ListApi.as_view(),name='job_list_api'),
    path('api/jobs/<int:id>',viewsapi.Job_DetailApi.as_view(),name='job_detail_api'),
    path('api/category',viewsapi.Category_ListApi.as_view(),name='category_list_api'),
    path('api/category/<int:id>',viewsapi.Category_DetailApi.as_view(),name='category_detail_api'),
    path('api/apply',viewsapi.Apply_ListApi.as_view(),name='apply_list_api'),
    path('api/apply/<int:id>',viewsapi.Apply_DetailApi.as_view(),name='apply_detail_api'),
    #End of Generic Class Based Views Api

    #Function Based Views Api
    path('api/jobsfunc',viewsapi.job_list_func_api , name='job_list_func_api'),
    path('api/jobsfunc/<int:id>',viewsapi.job_detail_func_api , name='job_detail_func_api'),
    path('api/categoryfunc',viewsapi.Category_list_func_api , name='Category_list_func_api'),
    path('api/categoryfunc/<int:id>',viewsapi.Category_detail_func_api , name='Category_detail_func_api'),
    path('api/applyfunc',viewsapi.Apply_list_func_api , name='Apply_list_func_api'),
    path('api/applyfunc/<int:id>',viewsapi.Apply_detail_func_api , name='Apply_detail_func_api'),
    #End of Function Based Views Api
    
]

project/urls.py
from unicodedata import name
from django import views
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace="accounts")),
    path('admin/', admin.site.urls),
    path('jobs/',include('job.urls',namespace="jobs")),
    path('contacts/',include('contact.urls',namespace="contact")),
    path('api-auth/',include("rest_framework.urls")),
    path('blog/',include('blog.urls',namespace="blogs")),
    path('',include('home.urls',namespace="homepage")),
    
]

urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify

# Create your models here.
def image_upload(instance,filename):
    txt='imgpost_'
    imagename,extension=filename.split('.')
    return "post/%s%s.%s"%(txt,instance.id,extension)


class Post(models.Model):

    title =  models.CharField(max_length=200, unique=True)
    slug=models.SlugField(blank=True,null=True)
    author = models.ForeignKey(User,related_name='post_owner',on_delete=models.CASCADE)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    image=models.ImageField(upload_to=image_upload)
    content = models.TextField()


    class Meta:
        ordering = ['-created_on']

    def save(self,*args,**kwargs):
        self.slug=slugify(self.title)
        super(Post,self).save(*args, **kwargs)

    def __str__(self) :
        return self.title

class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    username = models.CharField(max_length=25)
    email = models.EmailField()
    body = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['date_added']

blog/forms.py
from django import forms

from .models import Comment,Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields="__all__"
        exclude=('slug','author','created_on','updated_on')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['email','body']

blog/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from django.urls import reverse
from .models import Post
from .forms import CommentForm,PostForm
from django.views import generic 
from django.contrib.auth.decorators import login_required

# Create your views here.

 
def blog_list(request):
    blog_list = Post.objects.all()  # Post modelidan barcha bloglarni olish
    paginator = Paginator(blog_list, 10)  # Har bir sahifada 10 ta post
    page_number = request.GET.get('page')  # URL'dan sahifa raqamini olish
    page_obj = paginator.get_page(page_number)  # Sahifani olish

    context = {'blogs': page_obj}  # Sahifalash natijasini contextga qo'shish
    return render(request, 'blog/blog_list.html', context)  # Natijani shablonga yuborish


@login_required
def blog_detail(request,slug):
    blog_detail=Post.objects.get(slug=slug)
    if request.method=='POST':
        form=CommentForm(request.POST,request.FILES)
        if form.is_valid():
            myform=form.save(commit=False)
            myform.post=blog_detail
            myform.username=str(request.user)
            myform.save()
            return redirect('blogs:blog_detail',slug=slug)
            form=CommentForm() #this line is for clear all form fields after submitting
            print('Succesfully Submit')
    else:
        form=CommentForm()


    context={'blog':blog_detail,'CommentForm':form}
    return render(request,'blog/blog_detail.html',context)

@login_required
def create_post(request):


    if request.method=="POST":

        form=PostForm(request.POST,request.FILES)
        if form.is_valid():
            
            myform=form.save(commit=False)
            myform.author=request.user
            myform.save()
            form=PostForm() #this line is for clear all form fields after submitting
            return redirect(reverse('blogs:blog_list'))
            
            
    else:
        form=PostForm()
    
    return render(request,'blog/create_post.html',{'CREATEPOSTFORM':form})

blog/templates/blog/blog_detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}

    <!-- bradcam_area  -->
    {% block body %}
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>{{blog.title}}</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <!-- job_listing_area_start  -->
    <div class="job_listing_area plus_padding">
        <div class="container">
            <div class="row">
                
                <div class="col-lg-9">
                    


                    

                    <div class="job_lists m-0">
                        
                        <div class="row">
                            
                                <article class="blog_item">
                                    <div class="blog_item_img">
                                        <img class="card-img rounded-0" src="{{blog.image.url}}" alt="">
                                        <a href="#" class="blog_item_date">
                                            <h3>{{blog.created_on|date:'d'}}</h3>
                                            <p>{{blog.created_on|date:'M'}}</p>
                                        </a>
                                    </div>

                                    <div class="blog_details">
                                        <a class="d-inline-block" href="#">
                                            <h2>{{blog.title}}</h2>
                                        </a>
                                        <p>{{blog.content}}</p>
                                        <ul class="blog-info-link">
                                            <li><a href="#"><i class="fa fa-user"></i>Posted By: {{ blog.author }} At: {{blog.created_on|date:'d M o'}}</a></li>
                                            
                                        </ul>
                                    </div>
                                    


                                <div class="apply_job_form white-bg mt-3">
                                    <div class="comments-area">
                                        <h4>{{blog.comments.all.count}} Comments</h4>
                                        {% for comment in blog.comments.all %}
                                        <div class="comment-list">
                                           <div class="single-comment justify-content-between d-flex">
                                              <div class="user justify-content-between d-flex">
                                                 <div class="desc">
                                                    <h5>
                                                        <a href="#">{{ comment.username }}</a>
                                                     </h5>
                                                    
                                                    <div class="d-flex justify-content-between">
                                                       <div class="d-flex align-items-center">
                                                        <p class="comment">
                                                            {{ comment.body }}
                                                        </p>
                                                          <p class="date">{{ comment.date_added }}</p>
                                                       </div>
                                                       
                                                    </div>
                                                 </div>
                                              </div>
                                           </div>
                                        </div>
                                        {% empty %}
                                        <div class="notification">
                                            <p>No comments yet!</p>
                                        </div>
                                        {% endfor %}
                                    
                                    
                                    </div>

                                </div>

                                    
                                </article>
                                        

                                
                               

                            
                            
                        </div>

                        <div class="apply_job_form white-bg mt-3">
                            <h4>Leave A Comment</h4>
                            <form method='POST' enctype="multipart/form-data">
                                {% csrf_token %}
                                
                                    
                                    {% bootstrap_form CommentForm %}
                                    {% buttons %}
                                    <input type="submit" value="Send A Reply" class="boxed-btn3 w-100" />
                                    {% endbuttons %}
                                
                            </form>
                        </div>
                        

                        
                    </div>


                </div>

            </div>

        </div>

    </div>
    <!-- job_listing_area_end  -->

   {% endblock body %}

blog/templates/blog/blog_list.html
{% extends 'base.html' %}
{% load bootstrap4 %}

<!-- bradcam_area  -->
{% block body %}
<div>
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="bradcam_text">
                    <h3>Blog</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->

<!-- job_listing_area_start  -->
<div class="job_listing_area plus_padding">
    <div class="container">
        <div class="row">
            <div class="col-lg-12"> <!-- Changed from col-lg-9 to col-lg-12 -->
                <div class="recent_joblist_wrap">
                    <div class="recent_joblist white-bg">
                        <div class="row align-items-center">
                            <div class="col-md-6">
                                <div class="d-none d-lg-block">
                                    <a class="boxed-btn3" href="{% url 'blogs:blog_create_post' %}">Create Post</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                
                <div class="recent_joblist_wrap">
                    <div class="recent_joblist white-bg">
                        <div class="row align-items-center">
                            <div class="col-md-6">
                                <h4>Post Listing</h4>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="job_lists m-0">
                    <div class="col-12 mb-5 mb-lg-0 p-0"> <!-- Changed from col-lg-8 to col-12 and added p-0 -->
                        <div class="blog_left_sidebar w-100"> <!-- Added w-100 -->
                            <div class="row w-100 mx-0"> <!-- Added w-100 and mx-0 -->
                                {% for blog in blogs %}
                                    <div class="col-12">
                                        {% include 'blog/blog_list_item.html' %}
                                    </div>
                                {% endfor %}
                            </div>
                        
                            {% if blogs.has_other_pages %}
                                <div class="row">
                                    <div class="col-lg-12">
                                        <div class="pagination_wrap">
                                            <ul>
                                                {% if blogs.has_previous %}
                                                    <li><a href="?page={{ blogs.previous_page_number }}"> <i class="ti-angle-left"></i> </a></li>
                                                {% endif %}
                        
                                                {% for i in blogs.paginator.page_range %}
                                                    <li><a href="?page={{ i }}"><span>{{ i }}</span></a></li>
                                                {% endfor %}
                        
                                                {% if blogs.has_next %}
                                                    <li><a href="?page={{ blogs.next_page_number }}"> <i class="ti-angle-right"></i> </a></li>
                                                {% endif %}
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- job_listing_area_end  -->
{% endblock body %}

blog/templates/blog/blog_list_item.html
{% load static %}
{% load bootstrap4 %}

{% block extra_css %}
  <link rel="stylesheet" href="{% static 'css/custom.css' %}" />
  <link rel="stylesheet" href="{% static 'css/base.css' %}" />
{% endblock %}

{% comment %} local css area {% endcomment %}
{% block local_css %}
  <style>
    .blog_item_img {
      overflow: hidden;
      border-radius: 12px;
      box-shadow: 0 1px 4px rgba(0,0,0,0.1);
    }
    
    .blog_item_img img {
      transition: transform 0.3s ease;
    }
    .blog_item_img:hover img {
      transform: scale(1.05);
    }

    .img {
        max-width: 100%;
        height: auto;
        clip-path: inset(0 0 0 0 round 12px);
    }

    .img_div { 
        clip-path: inset(0 0 0 0 round 12px);
    }
  </style>
{% endblock %}

{% comment %} blog list item {% endcomment %}

<article class="blog_item mb-5 blog_item_img">
  <a class="d-inline-block" href="{% url 'blogs:blog_detail' blog.slug %}">
    <div class="row">
      <div class="col-md-3 mb-3 mb-md-0">
        <div class=".img_div">
            <img class="rounded img" src="{{ blog.image.url }}" alt="{{ blog.title }}" />
        </div>
      </div>
      <div class="col-md-9">
        <div class="blog_details">
          <h2>{{ blog.title }}</h2>
          <p>
            {{ blog.content|slice:':200' }}{% if blog.content|length > 200 %}...{% endif %}
          </p>
          <ul class="blog-info-link list-unstyled">
            <li>
              <i class="fa fa-user"></i> Posted By: {{ blog.author }} At: {{ blog.created_on|date:'d M Y' }}
            </li>
          </ul>
        </div>
      </div>
    </div>
  </a>
</article>

blog/templates/blog/create_post.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 mx-auto">
                    
                    
                    
                    <div class="apply_job_form white-bg">
                        <h4>Write A New Post</h4>
                        <form method='POST' enctype="multipart/form-data">
                            {% csrf_token %}
                            {% bootstrap_form CREATEPOSTFORM %}
                            
                            
                            {% buttons %}
                                <button class="boxed-btn3 w-100" type="submit">Create New Post</button>
                            {% endbuttons %}

                                
                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>

    {% endblock body %}