accounts/urls.py
from accounts import views
from django.urls import path

from django.urls.conf import include


"""the app_name variable provided for {% url 'namespace-for-url-ofproject:the nameofviewinpath' and relate it with id%}"""
app_name='accounts'


urlpatterns = [
    path('register',views.register,name="register"),
    path('profile',views.profile,name="profile"),
    path('profile/edit',views.profile_edit,name="profile_edit"),
    path('logout',views.logout_view,name="logout"),
    
]

blog/urls.py
from unicodedata import name
from blog import views
from django.urls import path
from django.urls.conf import include
from blog import viewsapi
"""the app_name variable provided for {% url 'namespace-for-url-ofproject:the nameofviewinpath' and relate it with id%}"""
app_name='blog'


urlpatterns = [
    path('',views.blog_list,name="blog_list"),
    path('addpost',views.create_post,name="blog_create_post"),
    path('post_detail/<str:slug>',views.blog_detail,name="blog_detail"),
      #Generic Class Based Views Api
    path('api/post',viewsapi.Post_ListApi.as_view(),name='post_list_api'),
    path('api/post/<int:id>',viewsapi.Post_DetailApi.as_view(),name='post_detail_api'),
    path('api/comment',viewsapi.Comment_ListApi.as_view(),name='comment_list_api'),
    path('api/comment/<int:id>',viewsapi.Comment_DetailApi.as_view(),name='comment_detail_api'),

    #End of Generic Class Based Views Api

    #Function Based Views Api
    path('api/postfunc',viewsapi.Post_list_func_api , name='post_list_func_api'),
    path('api/postfunc/<int:id>',viewsapi.Post_detail_func_api , name='post_detail_func_api'),
    path('api/commentfunc',viewsapi.Comment_list_func_api , name='Comment_list_func_api'),
    path('api/commentfunc/<int:id>',viewsapi.Comment_detail_func_api , name='Comment_detail_func_api'),

    #End of Function Based Views Api
    
    
]

contact/urls.py
from contact import views
from django.urls import path

from django.urls.conf import include
from contact import viewsapi
"""the app_name variable provided for {% url 'namespace-for-url-ofproject:the nameofviewinpath' and relate it with id%}"""
app_name='contact'


urlpatterns = [
    path('',views.sendmsg,name="contact_sendmsg"),

          #Generic Class Based Views Api
    path('api/information',viewsapi.Information_ListApi.as_view(),name='information_list_api'),
    path('api/information/<int:id>',viewsapi.Information_DetailApi.as_view(),name='information_detail_api'),
    #End of Generic Class Based Views Api

    #Function Based Views Api
    path('api/informationfunc',viewsapi.information_list_func_api , name='information_list_func_api'),
    path('api/informationfunc/<int:id>',viewsapi.information_detail_func_api , name='information_detail_func_api'),


    #End of Function Based Views Api
    
    
    
]

job/urls.py
from unicodedata import name
from job import views
from django.urls import path

from django.urls.conf import include
from job import viewsapi
"""the app_name variable provided for {% url 'namespace-for-url-ofproject:the nameofviewinpath' and relate it with id%}"""
app_name='job'


urlpatterns = [
    path('',views.job_list,name="job_list"),
    path('add',views.add_job,name="add_job"),
    path('<str:slug>',views.job_detail,name="job_detail"),
    #Generic Class Based Views Api
    path('api/jobs',viewsapi.Job_ListApi.as_view(),name='job_list_api'),
    path('api/jobs/<int:id>',viewsapi.Job_DetailApi.as_view(),name='job_detail_api'),
    path('api/category',viewsapi.Category_ListApi.as_view(),name='category_list_api'),
    path('api/category/<int:id>',viewsapi.Category_DetailApi.as_view(),name='category_detail_api'),
    path('api/apply',viewsapi.Apply_ListApi.as_view(),name='apply_list_api'),
    path('api/apply/<int:id>',viewsapi.Apply_DetailApi.as_view(),name='apply_detail_api'),
    #End of Generic Class Based Views Api

    #Function Based Views Api
    path('api/jobsfunc',viewsapi.job_list_func_api , name='job_list_func_api'),
    path('api/jobsfunc/<int:id>',viewsapi.job_detail_func_api , name='job_detail_func_api'),
    path('api/categoryfunc',viewsapi.Category_list_func_api , name='Category_list_func_api'),
    path('api/categoryfunc/<int:id>',viewsapi.Category_detail_func_api , name='Category_detail_func_api'),
    path('api/applyfunc',viewsapi.Apply_list_func_api , name='Apply_list_func_api'),
    path('api/applyfunc/<int:id>',viewsapi.Apply_detail_func_api , name='Apply_detail_func_api'),
    #End of Function Based Views Api
    
]

project/urls.py
from unicodedata import name
from django import views
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace="accounts")),
    path('admin/', admin.site.urls),
    path('jobs/',include('job.urls',namespace="jobs")),
    path('contacts/',include('contact.urls',namespace="contact")),
    path('api-auth/',include("rest_framework.urls")),
    path('blog/',include('blog.urls',namespace="blogs")),
    path('',include('home.urls',namespace="homepage")),
    
]

urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Job Board</title>
    <meta name="description" content="">
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <!-- Custom CSS to override any problematic background images -->
    <style>
        body, html {
            background-image: none !important;
            background-color: #fff !important;
            height: 100%;
        }
        .container-fluid, .row, .col {
            background-image: none !important;
        }
        /* Fix for the gap between content and footer */
        .wrapper {
            display: flex;
            min-height: 100vh;
        }
        .sidebar {
            width: 250px;
            flex-shrink: 0;
        }
        .main-content {
            display: flex;
            flex-direction: column;
            flex: 1;
        }
        .content-area {
            flex: 1;
        }
        footer {
            margin-top: auto;
        }
    </style>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <!-- Bootstrap Icons instead of FontAwesome -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    {% block extra_css %}{% endblock %}
</head>

<body>
    <div class="wrapper">
        <!-- Sidebar / Left Menu -->
        {% include 'sidebar.html' %}

        <!-- Main Content Area -->
        <div class="main-content" style="margin-left: 250px;">
            <!-- Content Section -->
            <div class="content-area">
                {% block body %}
                {% endblock body %}
            </div>

            <!-- Footer Section -->
            <footer class="bg-dark text-white py-4">
                <div class="container">
                    <div class="row">
                        <!-- Company Info -->
                        <div class="col-md-3 mb-4">
                            <div class="mb-3">
                                <a href="#">
                                    <img src="{% static 'img/logo.png' %}" alt="Logo" class="img-fluid" style="max-height: 40px;">
                                </a>
                            </div>
                            <p>
                                finloan@support.com <br>
                                +10 873 672 6782 <br>
                                600/D, Green road, NewYork
                            </p>
                            <div class="social-links">
                                <ul class="list-inline">
                                    <li class="list-inline-item">
                                        <a href="#" class="text-white">
                                            <i class="bi bi-facebook"></i>
                                        </a>
                                    </li>
                                    <li class="list-inline-item">
                                        <a href="#" class="text-white">
                                            <i class="bi bi-google"></i>
                                        </a>
                                    </li>
                                    <li class="list-inline-item">
                                        <a href="#" class="text-white">
                                            <i class="bi bi-twitter"></i>
                                        </a>
                                    </li>
                                    <li class="list-inline-item">
                                        <a href="#" class="text-white">
                                            <i class="bi bi-instagram"></i>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        
                        <!-- Company Links -->
                        <div class="col-md-2 mb-4">
                            <h5 class="mb-3">Company</h5>
                            <ul class="list-unstyled">
                                <li class="mb-2"><a href="#" class="text-white text-decoration-none">About</a></li>
                                <li class="mb-2"><a href="#" class="text-white text-decoration-none">Pricing</a></li>
                                <li class="mb-2"><a href="#" class="text-white text-decoration-none">Carrier Tips</a></li>
                                <li class="mb-2"><a href="#" class="text-white text-decoration-none">FAQ</a></li>
                            </ul>
                        </div>
                        
                        <!-- Categories -->
                        <div class="col-md-3 mb-4">
                            <h5 class="mb-3">Category</h5>
                            <ul class="list-unstyled">
                                <li class="mb-2"><a href="#" class="text-white text-decoration-none">Design & Art</a></li>
                                <li class="mb-2"><a href="#" class="text-white text-decoration-none">Engineering</a></li>
                                <li class="mb-2"><a href="#" class="text-white text-decoration-none">Sales & Marketing</a></li>
                                <li class="mb-2"><a href="#" class="text-white text-decoration-none">Finance</a></li>
                            </ul>
                        </div>
                        
                        <!-- Subscribe Section -->
                        <div class="col-md-4 mb-4">
                            <h5 class="mb-3">Subscribe</h5>
                            <form class="mb-3">
                                <div class="input-group">
                                    <input type="email" class="form-control" placeholder="Enter your mail">
                                    <button class="btn btn-success" type="submit">Subscribe</button>
                                </div>
                            </form>
                            <p>Esteem spirit temper too say adieus who direct esteem esteems luckily.</p>
                        </div>
                    </div>
                    
                    <!-- Copyright -->
                    <div class="row mt-4 border-top pt-3">
                        <div class="col-12 text-center">
                            <p class="mb-0">
                                Copyright &copy;<script>document.write(new Date().getFullYear())</script> 
                                All rights reserved | This template is made with 
                                <i class="bi bi-heart-fill text-danger"></i> by 
                                <a href="https://colorlib.com" target="_blank" class="text-white">Colorlib</a>
                            </p>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>

    <!-- Bootstrap JS Bundle with Popper -->
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

templates/base_generic.html
 {% extends 'base.html' %}

{% block body %}
    bradcam_area 
    <div>
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3></h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 mx-auto">
                   


                    
                        
                    
                    <div class="apply_job_form white-bg">
                        {% block content %}
                        
                        
                        
                        
                        {% endblock content  %}
                    </div>
                </div>
                
            </div>
        </div>
    </div>

    {% endblock body %}

templates/sidebar.html
{% load static %}
{% load bootstrap4 %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/custom.css' %}">
<link rel="stylesheet" href="{% static 'css/base.css' %}">
{% endblock %}

<div class="sidebar bg-sidebar position-fixed h-100" style="width: 250px; z-index: 1030;">
    <div class="d-flex flex-column h-100 p-3">
        <!-- Logo -->
        <div class="mb-4 text-center">
            <a href="/" class="d-block">
                <img src="{% static 'img/logo.png' %}" alt="Logo" class="img-fluid">
            </a>
        </div>

        <!-- Navigation Links -->
        <nav class="w-100">
            <ul class="nav flex-column">
                <li class="nav-item">
                    <a class="nav-link text-dark mb-2" href="/">
                        <i class="bi bi-house-fill"></i> Home
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark mb-2" href="{% url 'blogs:blog_list' %}">
                        <i class="bi bi-file-text-fill"></i> Blog
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark mb-2" href="{% url 'jobs:job_list' %}">
                        <i class="bi bi-search"></i> Browse Job
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark mb-2" href="{% url 'contact:contact_sendmsg' %}">
                        <i class="bi bi-person-fill"></i> Contact
                    </a>
                </li>
            </ul>
        </nav>

        <!-- Authentication Links -->
        <div class="mt-4 w-100 text-center">
            {% if request.user.is_authenticated %}
                <a href="{% url 'accounts:profile' %}" class="btn btn-outline-dark btn-sm w-100 mb-2">My Profile</a>
                <a href="{% url 'accounts:logout' %}" class="btn btn-outline-danger btn-sm w-100">Log Out</a>
            {% else %}
                <a href="{% url 'accounts:register' %}" class="btn btn-outline-dark btn-sm w-100 mb-2">Register</a>
                <a href="{% url 'login' %}" class="btn btn-outline-dark btn-sm w-100">Log In</a>
            {% endif %}
        </div>

        <!-- Post Job Button -->
        <div class="mt-auto w-100 text-center mb-3">
            <a href="{% url 'jobs:add_job' %}" class="btn btn-primary w-100">Post a Job</a>
        </div>
    </div>
</div>